export const CREATE_JOB_STARTED = 'CREATE_JOB_STARTED';
export const CREATE_JOB = 'CREATE_JOB';

export const GET_ALL_JOBS_STARTED = 'GET_ALL_JOBS_STARTED';
export const GET_ALL_JOBS = 'GET_ALL_JOBS';
export const GET_COMPLETED_JOBS_STARTED = 'GET_COMPLETED_JOBS_STARTED';
export const GET_COMPLETED_JOBS = 'GET_COMPLETED_JOBS';

export const GET_JOB_STATUS_STARTED = 'GET_JOB_STATUS_STARTED';
export const GET_JOB_STATUS = 'GET_JOB_STATUS';
