export const CREATE_JOB_STARTED = 'CREATE_JOB_STARTED';
export const CREATE_JOB = 'CREATE_JOB';
export const CREATE_JOB_FAILED = 'CREATE_JOB_FAILED';

export const GET_ALL_JOBS_STARTED = 'GET_ALL_JOBS_STARTED';
export const GET_ALL_JOBS = 'GET_ALL_JOBS';
export const GET_COMPLETED_JOBS_STARTED = 'GET_COMPLETED_JOBS_STARTED';
export const GET_COMPLETED_JOBS = 'GET_COMPLETED_JOBS';

export const GET_JOB_STATUS_STARTED = 'GET_JOB_STATUS_STARTED';
export const GET_JOB_STATUS = 'GET_JOB_STATUS';

export const GET_ACTIVITY_STARTED = 'GET_ACTIVITY_STARTED';
export const GET_ACTIVITY = 'GET_ACTIVITY';
export const GET_ACTIVITIES_STARTED = 'GET_ACTIVITIES_STARTED';
export const GET_ACTIVITIES = 'GET_ACTIVITIES';

// Inventory Action Types
export const FETCH_INVENTORY = 'FETCH_INVENTORY';

// Trader Action types
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const SET_TRADER_DATA = "SET_TRADER_DATA";
